# Generated by Django 4.2.7 on 2023-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintuc',
            name='AnhChinh',
            field=models.ImageField(default='uploads/noimage.jpg', upload_to='uploads/'),
        ),
    ]
