# Generated by Django 4.2.7 on 2023-11-07 19:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuyenMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenChuyenMuc', models.CharField(max_length=255)),
                ('DuongDan', models.SlugField(blank=True, null=True)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chuyên Mục',
                'verbose_name_plural': 'Chuyên Mục',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=255, unique=True)),
                ('GiaKhuyenMai', models.IntegerField()),
                ('GiaBan', models.IntegerField()),
                ('PhanTramGiam', models.IntegerField(blank=True, null=True)),
                ('MoTaNgan', models.TextField(max_length=255)),
                ('MoTaDai', ckeditor.fields.RichTextField()),
                ('The', models.CharField(max_length=255)),
                ('AnhChinh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('AnhPhu3', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('DuongDan', models.SlugField(blank=True, null=True)),
                ('TrangThai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
            options={
                'verbose_name': 'Sản Phẩm',
                'verbose_name_plural': 'Sản Phẩm',
            },
        ),
    ]
