# Generated by Django 4.2.7 on 2023-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='AnhChinh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='AnhPhu1',
            field=models.ImageField(blank=True, default='uploads/default_image.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='AnhPhu2',
            field=models.ImageField(blank=True, default='uploads/default_image.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='AnhPhu3',
            field=models.ImageField(blank=True, default='uploads/default_image.jpg', null=True, upload_to='uploads/'),
        ),
    ]
