# Generated by Django 4.2.7 on 2023-11-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiThongTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaLoai', models.CharField(blank=True, max_length=255, null=True)),
                ('TenLoai', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NhaTaiTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhaTaiTro', models.CharField(max_length=255)),
                ('HinhAnh', models.ImageField(blank=True, default='uploads/1.png', null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name': 'Nhà Tài Trợ',
                'verbose_name_plural': 'Nhà Tài Trợ',
            },
        ),
        migrations.CreateModel(
            name='ThongTin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaTri', models.CharField(blank=True, max_length=255, null=True)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('LoaiThongTin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.loaithongtin')),
            ],
            options={
                'verbose_name': 'Cấu Hình',
                'verbose_name_plural': 'Cấu Hình',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=255)),
                ('MoTaNgan', models.CharField(max_length=255)),
                ('MoTaDai', models.CharField(max_length=255)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BannerTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BannerMid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
        migrations.CreateModel(
            name='BannerBottom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('HienThi', models.BooleanField(default=True)),
                ('ChuyenMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.chuyenmuc')),
            ],
        ),
    ]
