# Generated by Django 4.2.7 on 2023-12-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbottom',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bannermid',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bannertop',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='nhataitro',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='HinhAnh',
            field=models.ImageField(blank=True, default='uploads/noimage.jpg', null=True, upload_to='uploads/'),
        ),
    ]
