# Generated by Django 4.2.7 on 2023-11-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(blank=True, max_length=255, null=True)),
                ('MoTaNgan', models.TextField(blank=True, max_length=255, null=True)),
                ('GiaBan', models.IntegerField(blank=True, null=True)),
                ('SoLuong', models.IntegerField(default=1)),
                ('KhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
                ('SanPham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.sanpham')),
            ],
            options={
                'verbose_name': 'Giỏ Hàng',
                'verbose_name_plural': 'Giỏ Hàng',
            },
        ),
    ]
