# Generated by Django 4.2.7 on 2023-11-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoDienThoai', models.CharField(max_length=11)),
                ('DiaChi', models.CharField(max_length=11)),
                ('TongTien', models.IntegerField()),
                ('GhiChu', models.CharField(blank=True, max_length=150, null=True)),
                ('ThoiGian', models.DateTimeField(auto_now_add=True)),
                ('TrangThai', models.CharField(choices=[('cxl', 'Chưa Xử Lý'), ('dxl', 'Đã Xử Lý'), ('dcbh', 'Đang Chuẩn Bị Hàng'), ('dgh', 'Đang Giao Hàng'), ('dghh', 'Đã Giao Hàng'), ('khh', 'Khách Hàng Hủy'), ('adh', 'Admin Hủy')], default='cxl', max_length=25)),
                ('KhachHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.khachhang')),
            ],
            options={
                'verbose_name': 'Đơn Hàng',
                'verbose_name_plural': 'Đơn Hàng',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GiaBan', models.IntegerField(blank=True, null=True)),
                ('SoLuong', models.IntegerField(default=1)),
                ('TongTien', models.IntegerField(blank=True, null=True)),
                ('DonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.donhang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sanpham')),
            ],
            options={
                'verbose_name': 'Chi Tiết Đơn Hàng',
                'verbose_name_plural': 'Chi Tiết Đơn Hàng',
            },
        ),
    ]
